// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AudioConfig describes the Opus audio track.
 */
export class AudioConfig {
    /**
     * Creates a new AudioConfig instance.
     * @param {Partial<AudioConfig>} [$$source = {}] - The source object to create the AudioConfig.
     */
    constructor($$source = {}) {
        if (!("codec" in $$source)) {
            /**
             * "opus"
             * @member
             * @type {string}
             */
            this["codec"] = "";
        }
        if (!("samplerate" in $$source)) {
            /**
             * 48000
             * @member
             * @type {number}
             */
            this["samplerate"] = 0;
        }
        if (!("channelConfig" in $$source)) {
            /**
             * "1" or "2"
             * @member
             * @type {string}
             */
            this["channelConfig"] = "";
        }
        if (!("bitrate" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bitrate"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AudioConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AudioConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AudioConfig(/** @type {Partial<AudioConfig>} */($$parsedSource));
    }
}

/**
 * ConnStats is a snapshot of QUIC transport metrics for the active session,
 * polled by the debug panel via SessionService.Stats. RTTs are milliseconds;
 * byte/packet counters are cumulative since the connection opened. The panel
 * diffs successive snapshots to derive rates (throughput, loss %).
 */
export class ConnStats {
    /**
     * Creates a new ConnStats instance.
     * @param {Partial<ConnStats>} [$$source = {}] - The source object to create the ConnStats.
     */
    constructor($$source = {}) {
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }
        if (!("smoothedRttMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["smoothedRttMs"] = 0;
        }
        if (!("latestRttMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["latestRttMs"] = 0;
        }
        if (!("minRttMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["minRttMs"] = 0;
        }
        if (!("congestionBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["congestionBytes"] = 0;
        }
        if (!("bytesInFlight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytesInFlight"] = 0;
        }
        if (!("packetsSent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["packetsSent"] = 0;
        }
        if (!("packetsReceived" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["packetsReceived"] = 0;
        }
        if (!("packetsLost" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["packetsLost"] = 0;
        }
        if (!("bytesSent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytesSent"] = 0;
        }
        if (!("bytesReceived" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytesReceived"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnStats(/** @type {Partial<ConnStats>} */($$parsedSource));
    }
}

/**
 * LogEntry is one log record forwarded from the Go backend to the frontend.
 * The binding generator turns this into a typed event payload.
 */
export class LogEntry {
    /**
     * Creates a new LogEntry instance.
     * @param {Partial<LogEntry>} [$$source = {}] - The source object to create the LogEntry.
     */
    constructor($$source = {}) {
        if (!("time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["time"] = "";
        }
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["level"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("attrs" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["attrs"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogEntry}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("attrs" in $$parsedSource) {
            $$parsedSource["attrs"] = $$createField3_0($$parsedSource["attrs"]);
        }
        return new LogEntry(/** @type {Partial<LogEntry>} */($$parsedSource));
    }
}

/**
 * MediaChunk carries one encoded frame from a remote peer to the frontend,
 * where WebCodecs decodes and renders it.
 * 
 * GroupID/ObjectID are the absolute MoQ coordinates of the object (§11.4.2).
 * The frontend needs them to restore decode order: each video GOP is its own
 * subgroup = its own QUIC stream, and the subscriber reads streams
 * concurrently (one goroutine per subgroup), so chunks from adjacent GOPs can
 * reach the frontend out of order over a lossy link. The player feeds frames
 * to the decoder in (GroupID, ObjectID) order and jumps to the newest keyframe
 * rather than decoding stale deltas against a reset reference — which is what
 * produced the severe smearing seen against a remote relay.
 */
export class MediaChunk {
    /**
     * Creates a new MediaChunk instance.
     * @param {Partial<MediaChunk>} [$$source = {}] - The source object to create the MediaChunk.
     */
    constructor($$source = {}) {
        if (!("participantId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["participantId"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * "video" | "audio"
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("data" in $$source)) {
            /**
             * base64-encoded codec bytes
             * @member
             * @type {string}
             */
            this["data"] = "";
        }
        if (!("timestampMicros" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timestampMicros"] = 0;
        }
        if (!("keyframe" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["keyframe"] = false;
        }
        if (!("groupId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["groupId"] = 0;
        }
        if (!("objectId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["objectId"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MediaChunk instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MediaChunk}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MediaChunk(/** @type {Partial<MediaChunk>} */($$parsedSource));
    }
}

/**
 * RemoteLeft signals a peer withdrew its namespace.
 */
export class RemoteLeft {
    /**
     * Creates a new RemoteLeft instance.
     * @param {Partial<RemoteLeft>} [$$source = {}] - The source object to create the RemoteLeft.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteLeft instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RemoteLeft}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemoteLeft(/** @type {Partial<RemoteLeft>} */($$parsedSource));
    }
}

/**
 * RemoteParticipant announces a discovered peer and its track configuration.
 */
export class RemoteParticipant {
    /**
     * Creates a new RemoteParticipant instance.
     * @param {Partial<RemoteParticipant>} [$$source = {}] - The source object to create the RemoteParticipant.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {VideoConfig | null | undefined}
             */
            this["video"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AudioConfig | null | undefined}
             */
            this["audio"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteParticipant instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RemoteParticipant}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("video" in $$parsedSource) {
            $$parsedSource["video"] = $$createField1_0($$parsedSource["video"]);
        }
        if ("audio" in $$parsedSource) {
            $$parsedSource["audio"] = $$createField2_0($$parsedSource["audio"]);
        }
        return new RemoteParticipant(/** @type {Partial<RemoteParticipant>} */($$parsedSource));
    }
}

/**
 * VideoConfig describes the H.264 video track. The frontend fills it once its
 * WebCodecs VideoEncoder is configured.
 */
export class VideoConfig {
    /**
     * Creates a new VideoConfig instance.
     * @param {Partial<VideoConfig>} [$$source = {}] - The source object to create the VideoConfig.
     */
    constructor($$source = {}) {
        if (!("codec" in $$source)) {
            /**
             * e.g. "avc1.42E01F"
             * @member
             * @type {string}
             */
            this["codec"] = "";
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }
        if (!("framerate" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["framerate"] = 0;
        }
        if (!("bitrate" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bitrate"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VideoConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VideoConfig(/** @type {Partial<VideoConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = VideoConfig.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = AudioConfig.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
