// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SessionService establishes and holds a MoQ (Media over QUIC Transport)
 * client session on behalf of the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Join establishes a MoQ session against the relay at addr. It blocks until
 * the QUIC connection and MOQT SETUP handshake complete (or fail). Throughout
 * establishment, every backend log line is proxied to the frontend as a
 * "moq:log" event via the context logger, so the UI can render progress live.
 * @param {string} addr
 * @returns {$CancellablePromise<void>}
 */
export function Join(addr) {
    return $Call.ByID(1641025405, addr);
}

/**
 * Leave tears down the current session, returning the UI to its initial state.
 * It is safe to call when no session is open.
 * @returns {$CancellablePromise<void>}
 */
export function Leave() {
    return $Call.ByID(4266125548);
}

/**
 * PublishAudioChunk forwards one Opus frame (the bytes of a WebCodecs
 * EncodedAudioChunk) to the audio track. The data arrives as a base64 string
 * on the wire; Wails (via encoding/json) decodes it into the []byte for us.
 * @param {string} data
 * @param {number} timestampMicros
 * @returns {$CancellablePromise<void>}
 */
export function PublishAudioChunk(data, timestampMicros) {
    return $Call.ByID(2935103691, data, timestampMicros);
}

/**
 * PublishVideoChunk forwards one H.264 access unit (the bytes of a WebCodecs
 * EncodedVideoChunk) to the video track. timestampMicros is the chunk's
 * presentation timestamp in microseconds. The data arrives as a base64 string
 * on the wire; Wails (via encoding/json) decodes it into the []byte for us.
 * @param {string} data
 * @param {number} timestampMicros
 * @param {boolean} keyframe
 * @returns {$CancellablePromise<void>}
 */
export function PublishVideoChunk(data, timestampMicros, keyframe) {
    return $Call.ByID(3509541092, data, timestampMicros, keyframe);
}

/**
 * StartPublishing publishes the catalog, video, and audio tracks for the
 * announced room. The frontend calls this once its WebCodecs encoders are
 * configured, before sending any media chunks.
 * @param {$models.VideoConfig} video
 * @param {$models.AudioConfig} audio
 * @returns {$CancellablePromise<void>}
 */
export function StartPublishing(video, audio) {
    return $Call.ByID(648899046, video, audio);
}

/**
 * StartSubscribing begins discovering other participants via SUBSCRIBE_NAMESPACE
 * and subscribing to their tracks. The frontend calls this from the call screen
 * once its remote-media event listeners are attached.
 * @returns {$CancellablePromise<void>}
 */
export function StartSubscribing() {
    return $Call.ByID(2704777838);
}

/**
 * Stats returns a snapshot of the current QUIC connection's transport metrics
 * for the debug panel. It is safe to call with no session open (it reports
 * Connected=false and zeroed counters).
 * @returns {$CancellablePromise<$models.ConnStats>}
 */
export function Stats() {
    return $Call.ByID(3717796760).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ConnStats.createFrom;
