// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as main$0 from "../../../../yandex/moq/apps/tlmst/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "moq:log": main$0.LogEntry;
            "moq:media-chunk": main$0.MediaChunk;
            "moq:participant-joined": main$0.RemoteParticipant;
            "moq:participant-left": main$0.RemoteLeft;
        }
    }
}
