//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as main$0 from "../../../../floatdrop/moq-go/apps/tlmst/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "moq:log": $$createType0,
        "moq:media-chunk": $$createType1,
        "moq:participant-joined": $$createType2,
        "moq:participant-left": $$createType3,
    }));
}

// Private type creation functions
const $$createType0 = main$0.LogEntry.createFrom;
const $$createType1 = main$0.MediaChunk.createFrom;
const $$createType2 = main$0.RemoteParticipant.createFrom;
const $$createType3 = main$0.RemoteLeft.createFrom;

configure();
